import express from "express";import {Pool} from "pg";import crypto from "node:crypto";import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";
const app=express();app.use(express.json({limit:"20mb"}));const __dirname=path.dirname(fileURLToPath(import.meta.url));const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes("render.com")?{rejectUnauthorized:false}:undefined});
const jobs=new Map();
async function db(){if(!process.env.DATABASE_URL)return;await pool.query(`create table if not exists cineforge_jobs(id text primary key,status text not null,video_url text,error text,created_at timestamptz default now())`)}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
app.get("/api/_healthcheck",async(_,res)=>{try{await db();res.json({ok:true,service:"cineforge-ai"})}catch(e){res.status(503).json({ok:false,error:e.message})}});
app.get("/api/provider-status",async(_,res)=>{res.json({provider:process.env.VIDEO_PROVIDER||"hf_ltx_fast",status:process.env.HF_TOKEN?"configured":"token_required"})});
async function hfGenerate({prompt,image}){const space=process.env.HF_SPACE_URL||"https://lightricks-ltx-video-distilled.hf.space";const apiName=image?"image_to_video":"text_to_video";let inputImage=null;if(image){const m=String(image).match(/^data:([^;]+);base64,(.+)$/);if(!m)throw new Error("Invalid reference image.");const bytes=Buffer.from(m[2],"base64");const fd=new FormData();fd.append("files",new Blob([bytes],{type:m[1]}),"reference.png");const up=await fetch(space+"/gradio_api/upload",{method:"POST",body:fd});if(!up.ok)throw new Error("Video provider image upload failed.");const u=await up.json();inputImage=Array.isArray(u)?{path:u[0],meta:{_type:"gradio.FileData"}}:{path:u.path,meta:{_type:"gradio.FileData"}}}
const data=[prompt,"worst quality, inconsistent motion, blurry, jittery, distorted",inputImage,null,432,768,apiName==="image_to_video"?"image-to-video":"text-to-video",5,9,42,true,3,false];
const call=await fetch(space+"/gradio_api/call/"+apiName,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({data})});if(!call.ok)throw new Error("Video provider rejected the generation request.");const c=await call.json();const ev=c.event_id;if(!ev)throw new Error("Video provider returned no event id.");const stream=await fetch(space+"/gradio_api/call/"+apiName+"/"+ev);if(!stream.ok)throw new Error("Video provider event stream failed.");const text=await stream.text();const lines=text.split("\n").filter(x=>x.startsWith("data:"));for(const line of lines.reverse()){try{const d=JSON.parse(line.slice(5).trim());if(Array.isArray(d)&&d.length){const v=d[d.length-1];const url=v?.url||v?.video?.url||v?.path;if(url)return url}}catch{}}throw new Error("Video provider finished without a video URL.")};
app.post("/api/generate-video",async(req,res)=>{const id=crypto.randomUUID();const j={id,status:"queued"};jobs.set(id,j);if(process.env.DATABASE_URL)db().then(()=>pool.query("insert into cineforge_jobs(id,status) values($1,$2) on conflict do nothing",[id,"queued"])).catch(()=>{});res.json(j);(async()=>{j.status="processing";try{if(!process.env.HF_TOKEN)throw new Error("HF_TOKEN is not configured on the CineForge service.");const url=await hfGenerate({prompt:req.body?.prompt||"",image:req.body?.image||""});j.status="completed";j.videoUrl=url;if(process.env.DATABASE_URL)await pool.query("update cineforge_jobs set status=$1,video_url=$2 where id=$3",["completed",url,id])}catch(e){j.status="failed";j.error=e.message||"Generation failed";if(process.env.DATABASE_URL)await pool.query("update cineforge_jobs set status=$1,error=$2 where id=$3",["failed",j.error,id]).catch(()=>{})}})()});
app.get("/api/generate-video/:id",(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:"Job not found. Keep this tab open while generation runs."});res.json(j)});
const dist=path.join(__dirname,"dist");app.use(express.static(dist));app.get("*",(req,res)=>res.sendFile(path.join(dist,"index.html")));const port=process.env.PORT||10000;db().then(()=>app.listen(port,()=>console.log("CineForge listening on "+port))).catch(e=>{console.error(e);app.listen(port,()=>console.log("CineForge listening without DB"))});