import {ChangeEvent,useEffect,useRef,useState} from "react";
import {Download,Film,Image as ImageIcon,Loader2,Menu,Play,Plus,Settings,Sparkles,Upload,X} from "lucide-react";
type Job={id:string;status:string;videoUrl?:string;error?:string};
const api=async(path:string,init?:RequestInit)=>{const r=await fetch(path,{credentials:"same-origin",...init});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{d={error:t}}if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d};
export default function App(){
 const [prompt,setPrompt]=useState("");const [mode,setMode]=useState<"text"|"image">("text");const [image,setImage]=useState("");const [imageName,setImageName]=useState("");const [duration,setDuration]=useState("5");const [ratio,setRatio]=useState("16:9");const [resolution,setResolution]=useState("480p");const [job,setJob]=useState<Job|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [provider,setProvider]=useState("checking");const inputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{api("/api/provider-status").then(x=>setProvider(x.provider+" · "+x.status)).catch(()=>setProvider("unavailable"))},[]);
 const choose=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){setError("Image must be 8 MB or smaller.");return}const rd=new FileReader();rd.onload=()=>{setImage(String(rd.result||""));setImageName(f.name);setError("")};rd.readAsDataURL(f)};
 const generate=async()=>{setError("");if(!prompt.trim()){setError("Describe the video you want to create.");return}if(mode==="image"&&!image){setError("Choose a reference image first.");return}setBusy(true);setJob(null);try{const x=await api("/api/generate-video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,image,aspectRatio:ratio,resolution,duration:Number(duration)})});let j:Job=x;setJob(j);for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,3000));const s=await api("/api/generate-video/"+j.id);setJob(s);if(s.status==="completed"||s.status==="failed"){if(s.status==="failed")setError(s.error||"Video generation failed.");break}}}catch(e:any){setError(e.message||"Video generation failed.")}finally{setBusy(false)}};
 return <div className="shell"><header><div className="brand"><div className="logo"><Film size={20}/></div><div><b>CineForge AI</b><span>AI video studio</span></div></div><div className="provider"><span className="dot"/> {provider}</div><button className="icon"><Settings size={18}/></button></header>
 <main><section className="hero"><p className="eyebrow"><Sparkles size={15}/> CINEMATIC GENERATION</p><h1>Bring your ideas to<br/><em>cinematic life.</em></h1><p className="sub">Create short AI videos from text or a reference image. Generate, preview and download from one workspace.</p></section>
 <section className="workspace"><div className="panel composer"><div className="tabs"><button className={mode==="text"?"active":""} onClick={()=>setMode("text")}><Film size={16}/> Text to video</button><button className={mode==="image"?"active":""} onClick={()=>setMode("image")}><ImageIcon size={16}/> Image to video</button></div>
 <label>Prompt</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="A cinematic aerial shot of a futuristic Lagos skyline at golden hour, slow camera movement..."/>
 {mode==="image"&&<div className="upload" onClick={()=>inputRef.current?.click()}><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={choose}/><Upload size={20}/><b>{imageName||"Upload a reference image"}</b><small>PNG, JPG or WEBP · max 8 MB</small>{image&&<img src={image} alt="Reference"/>}</div>}
 <div className="controls"><label>Aspect<select value={ratio} onChange={e=>setRatio(e.target.value)}><option>16:9</option><option>9:16</option><option>1:1</option></select></label><label>Resolution<select value={resolution} onChange={e=>setResolution(e.target.value)}><option>480p</option><option>720p</option></select></label><label>Duration<select value={duration} onChange={e=>setDuration(e.target.value)}><option>3</option><option>5</option><option>8</option></select></label></div>
 {error&&<div className="error">{error}</div>}<button className="generate" onClick={generate} disabled={busy}>{busy?<><Loader2 className="spin" size={18}/> Generating…</>:<><Play size={18}/> Generate video</>}</button><small className="quota">Provider: {provider}. Generation time and free quotas depend on the selected provider.</small></div>
 <div className="panel preview"><div className="previewHead"><b>Preview</b>{job?.status&&<span>{job.status}</span>}</div>{job?.videoUrl?<video src={job.videoUrl} controls playsInline/><div className="actions"><a href={job.videoUrl} download><Download size={16}/> Download</a><button onClick={()=>setJob(null)}><X size={16}/> Clear</button></div>:<div className="empty"><Film size={38}/><b>Your generated video appears here</b><span>Write a prompt and start a generation.</span>{busy&&<Loader2 className="spin" size={20}/>}</div>}</div></section>
 <section className="cards"><div><Plus size={18}/><b>Text + image workflows</b><span>Use either a prompt or a reference image.</span></div><div><Sparkles size={18}/><b>Provider-ready backend</b><span>Video provider can be switched without changing the UI.</span></div><div><Menu size={18}/><b>Simple creator workflow</b><span>Generate, preview and download in one place.</span></div></section></main><footer>CineForge AI · Independent service · Not connected to AI Media Studio</footer></div>
}